[package]
name = "readability"
version = "0.1.0"
authors = ["Paul Loyd <pavelko95@gmail.com>"]

[dependencies]
kuchiki = "^0.4.1"
lazy_static = "^0.2.1"
regex = "^0.2.1"
html5ever-atoms = "^0.1.3"
url = "^1.4.0"
